color.Germans=626262
color.Poland=BC1E2C
color.Neutral=E8DFC7
color.Impassable=333333

map.width=1024
map.height=768
map.hasRelief=false
map.showTerritoryNames=false
map.mapBlends=false
map.scrollWrapX=false
map.scrollWrapY=false
units.scale=0.9000
units.width=40
units.height=40

screenshot.title.x=30
screenshot.title.y=30
screenshot.title.color=202020
screenshot.title.font.size=22
screenshot.stats.enabled=true
screenshot.stats.x=30
screenshot.stats.y=710
screenshot.stats.text.color=202020
screenshot.stats.border.color=F0E8D0
