# Runs all build checks on any pull request or merges to main
name: Verify
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Run Build Checks
        shell: bash
        run: |
          set -o pipefail
          ./verify --exclude-task spotlessApply 2>&1 | tee verify.log
      - name: Upload Verify log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-log
          path: verify.log
          if-no-files-found: error
